# Generated by Django 2.2.4 on 2024-06-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationApp', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2024-06-19', max_length=20, verbose_name='出生日期'),
        ),
    ]
