# Generated by Django 2.2.4 on 2024-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationApp', '0003_auto_20240619_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2024-06-20', max_length=20, verbose_name='出生日期'),
        ),
    ]
