# Generated by Django 2.2.4 on 2024-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationApp', '0004_auto_20240620_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2024-06-23', max_length=20, verbose_name='出生日期'),
        ),
    ]
