# Generated by Django 2.2.4 on 2024-06-19 02:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' 藏品标题')),
                ('description', models.TextField(verbose_name='藏品详情描述')),
                ('productType', models.CharField(choices=[('瓷器', '瓷器'), ('青铜器', '青铜器'), ('书法', '书法')], max_length=50, verbose_name='藏品类型')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '藏品',
                'verbose_name_plural': '藏品',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Product/', verbose_name='藏品图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='collectionApp.Product', verbose_name='藏品')),
            ],
            options={
                'verbose_name': '藏品图片',
                'verbose_name_plural': '藏品图片',
            },
        ),
    ]
